### ISSUE TITLE
Asynchronität in express-waf.js

### ISSUE THREAD

**Issue by DaspawnW** [DSALabHRW/express-waf#1]
die Iteration über die Module, die sich erfolgreich registriert haben und das abschließende Callback müssen über eine rekursive-Funktion gelöst werden, da sonst asynchronität in Gefahr.
Beispiel: Ein Modul will Zugriff auf IO nutzen, dann asynchronität nicht mehr sichergestellt.

**Comment by DaspawnW** [comment]
``` javascript
function recursiveCall = function(i, cb) {     //req, res nicht umbedingt nötig, da call by refference
   if(i >= modules.length) {
      cb();
   } else {
      modules[i].check(req, res, function() {
          recursiveCall(i++, cb);
      });
   }
}
```

**Comment by marc-dsalab** [comment]
Hmm, versteht ich nicht so ganz. Aus meiner Sicht ist es eigentlich genau andersrum: die synchronität, die die alte Methode voraussetzt, ist in Gefahr. Oder sehe och das falsch?

Am 18.11.2014 19:02 schrieb DaspawnW notifications@github.com:

die Iteration über die Module, die sich erfolgreich registriert haben und das abschließende Callback müssen über eine rekursive-Funktion gelöst werden, da sonst asynchronität in Gefahr.
Beispiel: Ein Modul will Zugriff auf IO nutzen, dann asynchronität nicht mehr sichergestellt.

**Comment by DaspawnW** [comment]
Nehmen wir das Beispiel wir wollen Nutzer blockieren, die häufig auf das System zugreifen.
Dann speichern wir vielleicht die IP's irgendwo in einer lokalen Datei ab, oder auch in der Datenbank.
Dann würde die Check-Methode gegen die Datenbank oder eine lokale Datei prüfen und feststellen, dass der Nutzer häufig zugegriffen hat oder eben nicht. Entsprechend müssen wir wieder in die Datenbank schreiben.
Erst wenn das alles passiert ist soll das nächste Modul durchlaufen bzw. die eigentliche Abarbeitung des Requests beginnen, sonst kann es schlimmstenfalls vorkommen, dass die Check-Methoden noch gar nicht durchgelaufen sind, weil diese viel auf IO interagieren, aber der Request bereits beantwortet wurde, weil dieser nicht wartet bis alle Checks durchgelaufen sind.

**Comment by marc-dsalab** [comment]
Das ist ja genau das was ich meine. Ich formuliere es mal anders:

Die bisherige Implementierung geht davon aus, dass mehr oder weniger alle Module der Reihe nach durchlaufen werden und das wenn man damit durch ist, ohne das etwas aufgefallen ist, der Callback ausgelöst werden kann, also der Request weiter bearbeitet werden kann (z.B. In die entsprechende Methode des HTTP Verbs übergeben werden kann). Das funktioniert auch, solange keine der Check Methoden irgendetwas mit IO macht (z.B. auf die DB zugreift um zu schauen ob der Host gesperrt ist, oder zum Beispiel einen eigenen HTTP Request macht, um zu sehen ob der Request zulässig ist). Wenn aber doch ein IO passiert, dann ist die Annahme der Synchronität der Aufrufe nicht mehr gewährleistet. Der vorgeschlagene Fix behebt das Problem und sorgt dafür das der Callback erst ausgeführt wird, wenn wirklich alle Module abgearbeitet sind, stellt also das ursprünglich angedachte Verhalten wieder her.

Von: DaspawnW <notifications@github.com<mailto:notifications@github.com>>
Antworten an: DSALabHRW/express-waf <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Dienstag, 18. November 2014 20:01
An: DSALabHRW/express-waf <express-waf@noreply.github.com<mailto:express-waf@noreply.github.com>>
Cc: Marc Jansen <marc.jansen@hs-ruhrwest.de<mailto:marc.jansen@hs-ruhrwest.de>>
Betreff: Re: [express-waf] Asynchronität in express-waf.js (#1)

Nehmen wir das Beispiel wir wollen Nutzer blockieren, die häufig auf das System zugreifen.
Dann speichern wir vielleicht die IP's irgendwo in einer lokalen Datei ab, oder auch in der Datenbank.
Dann würde die Check-Methode gegen die Datenbank oder eine lokale Datei prüfen und feststellen, dass der Nutzer häufig zugegriffen hat oder eben nicht. Entsprechend müssen wir wieder in die Datenbank schreiben.
Erst wenn das alles passiert ist soll das nächste Modul durchlaufen bzw. die eigentliche Abarbeitung des Requests beginnen, sonst kann es schlimmstenfalls vorkommen, dass die Check-Methoden noch gar nicht durchgelaufen sind, weil diese viel auf IO interagieren, aber der Request bereits beantwortet wurde, weil dieser nicht wartet bis alle Checks durchgelaufen sind.
