### ISSUE TITLE
Auswirkung eines System-Absturz

### ISSUE THREAD

**Issue by DaspawnW** [DSALabHRW/express-waf#14]
Was passiert mit den geblockten Usern, wenn die nodejs Instanz abstürzt.
So wie ich das sehe verlassen diese niemals wieder die MongoDB und sind für immer gesperrt.

Es gäbe daher aus meiner Sicht nur zwei Alternativen:
1. Bei einem neustart des Servers alle geblockten User wieder freizugeben
2. In die MongoDB ein Zeitflag mit zu schreiben und neben der ip in der datenbank auch das zeitflag zu überprüfen und bei einem neustart des Servers alle veralteten Blocks zu löschen?

**Comment by marc-dsalab** [comment]
Since this is open source, i switch to english: after a restart, the list in the MongoDB should be flushed...

**Comment by DaspawnW** [comment]
Ok, will be implemented in next version

**Comment by henning96** [comment]
I'm going to check on that issue in my internship.

**Comment by marc-dsalab** [comment]
Way to late Henning... :)
